<h1>Tabla de Contenidos<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#OPERACIONES-CON-COLUMNAS-O-FILAS" data-toc-modified-id="OPERACIONES-CON-COLUMNAS-O-FILAS-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>OPERACIONES CON COLUMNAS O FILAS</a></span><ul class="toc-item"><li><span><a href="#Multiplicar-una-columna-por-un-número" data-toc-modified-id="Multiplicar-una-columna-por-un-número-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Multiplicar una columna por un número</a></span></li><li><span><a href="#Suma-o-resta-de-columnas" data-toc-modified-id="Suma-o-resta-de-columnas-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Suma o resta de columnas</a></span></li><li><span><a href="#Multiplicación-y-División-de-columnas" data-toc-modified-id="Multiplicación-y-División-de-columnas-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Multiplicación y División de columnas</a></span></li><li><span><a href="#Potencia-pow(elemento,-potencia)" data-toc-modified-id="Potencia-pow(elemento,-potencia)-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Potencia pow(elemento, potencia)</a></span></li><li><span><a href="#Exponencial" data-toc-modified-id="Exponencial-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Exponencial</a></span></li></ul></li><li><span><a href="#Eliminar-columnas-con-drop" data-toc-modified-id="Eliminar-columnas-con-drop-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Eliminar columnas con drop</a></span></li><li><span><a href="#Filtros-en-Pandas" data-toc-modified-id="Filtros-en-Pandas-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Filtros en Pandas</a></span></li><li><span><a href="#FORMAS-DE-ORDENAR" data-toc-modified-id="FORMAS-DE-ORDENAR-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>FORMAS DE ORDENAR</a></span><ul class="toc-item"><li><span><a href="#Ordenando-las-filas-por-los-valores-de-una-columna" data-toc-modified-id="Ordenando-las-filas-por-los-valores-de-una-columna-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Ordenando las filas por los valores de una columna</a></span></li><li><span><a href="#Ordenando-las-filas-por-los-valores-de-varias-columnas:" data-toc-modified-id="Ordenando-las-filas-por-los-valores-de-varias-columnas:-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Ordenando las filas por los valores de varias columnas:</a></span></li></ul></li></ul></div>

In [2]:
import pandas as pd
import numpy as np
df_iris = pd.read_csv('Datos/iris.tab',sep='\t',skiprows=(1,2))

# COMPUTACIÓN CIENTÍFICA
# Situación Profesional 2
# Clase 3: Pandas
**Prof. Ricardo Piña - Erica Bongiovanni**

## OPERACIONES CON COLUMNAS O FILAS

Carguemos el archivo csv iris.tab en un dataframe de nombre df_iris

In [10]:
df_iris = pd.read_csv('Datos/iris.tab',sep='\t',skiprows=(1,2))
df_iris.head(10)

   sepal length  sepal width  petal length  petal width         iris
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

Cambie los nombres para que no tengan espacios ...

In [3]:
# Escriba aquí su código
df_iris.columns=['sepal_length' ,'sepal_width' ,'petal_length' ,'petal_width' ,'iris']

In [3]:
df_iris

     sepal_length  sepal_width  petal_length  petal_width            iris
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

### Multiplicar una columna por un número

Supongamos que necesitamos multiplicar por 2 la columna sepal_length, entonces simplemente hacemos:  
columna * 2

In [5]:
df_iris.sepal_width*2

0      7.0
1      6.0
2      6.4
3      6.2
4      7.2
      ...
145    6.0
146    5.0
147    6.0
148    6.8
149    6.0
Name: sepal_width, Length: 150, dtype: float64

Compare con la impresión del dataframe que hicimos antes y podrá verificar que los valores de la columna efectivamente han sido multiplicados por 2, **aunque estos cambios no sea han efectuado en el dataframe**, fijese:

In [6]:
df_iris

     sepal_length  sepal_width  petal_length  petal_width            iris
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

Si quisiéramos que se cambiara la columna, deberíamos asignarle el resultado obtenido. En este caso no deseamos hacerlo.

### Suma o resta de columnas

**columna + columna**  
**columna - columna**

Supongamos que necesitamos restar sepal_length - petal_length, simplemente podemos hacer lo siguiente:

In [7]:
df_iris.sepal_width -_df_iris.petal_length

0      2.1
1      1.6
2      1.9
3      1.6
4      2.2
      ...
145   -2.2
146   -2.5
147   -2.2
148   -2.0
149   -2.1
Length: 150, dtype: float64

De la misma manera que indicábamos con anterioridad, este resultado no se encuentra en el dataframe.   
Esta vez sí supongamos que deseamos **agregarlo** como una columna más del dataframe con el nombre de 'sl-pl'.

In [8]:
df_iris['sepwi-petlen']= df_iris.sepal_width -df_iris.petal_length
df_iris

,sepal_length,sepal_width,petal_length,petal_width,iris,sepwi-petlen
0,5.1,3.5,1.4,0.2,Iris-setosa,2.1
1,4.9,3.0,1.4,0.2,Iris-setosa,1.6
2,4.7,3.2,1.3,0.2,Iris-setosa,1.9
3,4.6,3.1,1.5,0.2,Iris-setosa,1.6
4,5.0,3.6,1.4,0.2,Iris-setosa,2.2
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,-2.2
146,6.3,2.5,5.0,1.9,Iris-virginica,-2.5
147,6.5,3.0,5.2,2.0,Iris-virginica,-2.2
148,6.2,3.4,5.4,2.3,Iris-virginica,-2.0
149,5.9,3.0,5.1,1.8,Iris-virginica,-2.1

### Multiplicación y División de columnas

**columna * columna**
**columna/columna**

En un caso como el del reconocimiento de la flor Iris por Machine Learning, seguramente sería de interés tener en una feature o variable con una aproximación a la superficie de los pétalos.  

Agregue esta columna con el nombre 'sup-pet'

In [14]:
# Escriba aquí su código
df_iris['sup+pet']=df_iris.petal_length * df_iris.petal_width
df_iris.head()

,sepal_length,sepal_width,petal_length,petal_width,iris,sepwi-petlen,sup-pet,sup-sep,sup+pet,sup+sep
0,5.1,3.5,1.4,0.2,Iris-setosa,2.1,0.28,17.85,0.28,17.85
1,4.9,3.0,1.4,0.2,Iris-setosa,1.6,0.28,14.70,0.28,14.70
2,4.7,3.2,1.3,0.2,Iris-setosa,1.9,0.26,15.04,0.26,15.04
3,4.6,3.1,1.5,0.2,Iris-setosa,1.6,0.30,14.26,0.30,14.26
4,5.0,3.6,1.4,0.2,Iris-setosa,2.2,0.28,18.00,0.28,18.00

Podríamos hacer lo mismo para los sépalos .. guárdelo en la columna 'sup-sep'

In [13]:
# Escriba aquí su código
df_iris['sup+sep']=df_iris.sepal_length * df_iris.sepal_width 
df_iris.head()

,sepal_length,sepal_width,petal_length,petal_width,iris,sepwi-petlen,sup-pet,sup-sep,sup+pet,sup+sep
0,5.1,3.5,1.4,0.2,Iris-setosa,2.1,0.28,17.85,0.28,17.85
1,4.9,3.0,1.4,0.2,Iris-setosa,1.6,0.28,14.70,0.28,14.70
2,4.7,3.2,1.3,0.2,Iris-setosa,1.9,0.26,15.04,0.26,15.04
3,4.6,3.1,1.5,0.2,Iris-setosa,1.6,0.30,14.26,0.30,14.26
4,5.0,3.6,1.4,0.2,Iris-setosa,2.2,0.28,18.00,0.28,18.00

Seguro que un problema de identificación de flores de las cuales conocemos las medidas, las relaciones entre las medidas también sería importantes, así que creemos una nueva variable llamada 'pet_l/pet_w' cuyos valores sean  la división de petal_length sobre petal_width.

In [16]:
# Escriba aquí su código
df_iris['plen/pwid'] = df_iris.petal_length/df_iris.petal_width
df_iris

,sepal_length,sepal_width,petal_length,petal_width,iris,sepwi-petlen,sup-pet,sup-sep,sup+pet,sup+sep,plen/pwid
0,5.1,3.5,1.4,0.2,Iris-setosa,2.1,0.28,17.85,0.28,17.85,7.000000
1,4.9,3.0,1.4,0.2,Iris-setosa,1.6,0.28,14.70,0.28,14.70,7.000000
2,4.7,3.2,1.3,0.2,Iris-setosa,1.9,0.26,15.04,0.26,15.04,6.500000
3,4.6,3.1,1.5,0.2,Iris-setosa,1.6,0.30,14.26,0.30,14.26,7.500000
4,5.0,3.6,1.4,0.2,Iris-setosa,2.2,0.28,18.00,0.28,18.00,7.000000
...,...,...,...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,-2.2,11.96,20.10,11.96,20.10,2.260870
146,6.3,2.5,5.0,1.9,Iris-virginica,-2.5,9.50,15.75,9.50,15.75,2.631579
147,6.5,3.0,5.2,2.0,Iris-virginica,-2.2,10.40,19.50,10.40,19.50,2.600000
148,6.2,3.4,5.4,2.3,Iris-virginica,-2.0,12.42,21.08,12.42,21.08,2.347826
149,5.9,3.0,5.1,1.8,Iris-virginica,-2.1,9.18,17.70,9.18,17.70,2.833333

### Potencia pow(elemento, potencia)
También podríamos elevar al cuadrado, al cubo o a la n los valores de alguna columna ...

Eleve al cuadrado los valores de petal_length, no los agregue al dataframe.

In [17]:
pow(df_iris.petal_length,2)

0       1.96
1       1.96
2       1.69
3       2.25
4       1.96
       ...
145    27.04
146    25.00
147    27.04
148    29.16
149    26.01
Name: petal_length, Length: 150, dtype: float64

In [18]:
df_iris.petal_length**2

0       1.96
1       1.96
2       1.69
3       2.25
4       1.96
       ...
145    27.04
146    25.00
147    27.04
148    29.16
149    26.01
Name: petal_length, Length: 150, dtype: float64

Las raíces también pueden calcularse como potencia.

### Exponencial 
$$ e^c $$

Daría por resultado cada elemento de la columna como exponente de e.

In [20]:
np.exp(df_iris.petal_length)
df_iris

,sepal_length,sepal_width,petal_length,petal_width,iris,sepwi-petlen,sup-pet,sup-sep,sup+pet,sup+sep,plen/pwid
0,5.1,3.5,1.4,0.2,Iris-setosa,2.1,0.28,17.85,0.28,17.85,7.000000
1,4.9,3.0,1.4,0.2,Iris-setosa,1.6,0.28,14.70,0.28,14.70,7.000000
2,4.7,3.2,1.3,0.2,Iris-setosa,1.9,0.26,15.04,0.26,15.04,6.500000
3,4.6,3.1,1.5,0.2,Iris-setosa,1.6,0.30,14.26,0.30,14.26,7.500000
4,5.0,3.6,1.4,0.2,Iris-setosa,2.2,0.28,18.00,0.28,18.00,7.000000
...,...,...,...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica,-2.2,11.96,20.10,11.96,20.10,2.260870
146,6.3,2.5,5.0,1.9,Iris-virginica,-2.5,9.50,15.75,9.50,15.75,2.631579
147,6.5,3.0,5.2,2.0,Iris-virginica,-2.2,10.40,19.50,10.40,19.50,2.600000
148,6.2,3.4,5.4,2.3,Iris-virginica,-2.0,12.42,21.08,12.42,21.08,2.347826
149,5.9,3.0,5.1,1.8,Iris-virginica,-2.1,9.18,17.70,9.18,17.70,2.833333

## Eliminar columnas con drop

Supongamos que queremos eliminar la columna sl-pl que creamos hacer un rato, podemos usar .drop:

documentación en: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html

In [41]:
df_iris = df_iris.drop('plen/pwid',axis=1)
df_iris.head()
# también se podría haber usado:
# df_iris.drop(columns=['sl-pl'])  y evitamos recordar el axis!

KeyError: "['plen/pwid'] not found in axis"

## Filtros en Pandas

Los filtros de tipo **.filter** en Pandas **NO** se usan para filtrar por el valor de los ítems (las celdas de Excel), sino que se utilizan para **filtrar por los valores o etiquetas de los índices de las columnas o de las filas**. No los veremos por el momento. 

Documentación: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.filter.html

Nuestro interés está en el proceso de **filtrado por valores de los items** y en este sentido es muy similar al funcionamiento de NumPy.  

En la jerga de Pandas en vez de filtrado se suele denominar como  

*__obtención de subconjuntos de filas que, por ejemplo, verifican cierto criterio__*.

Recordemos qué tenemos en nuestro dataframe:

In [43]:
df_iris[df_iris.sepal_length >= 5].head(4)

   sepal_length  sepal_width  petal_length  petal_width         iris
0           5.1          3.5           1.4          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa

Supongamos que deseamos ver todas las filas para las cuales el valor de sepal_length sea menor que 5.  
El procedimiento será muy similar al del NumPy.

In [44]:
df_iris[df_iris.sepal_length <= 5].head(4)

   sepal_length  sepal_width  petal_length  petal_width         iris
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Obtengamos las filas para las cuales el valor de sepal_length sea mayor que el doble del sepal_width

In [47]:
#Escriba aqui su código
df_iris[df_iris.sepal_length > 2 * df_iris.sepal_width ].head(4)

    sepal_length  sepal_width  petal_length  petal_width             iris
50           7.0          3.2           4.7          1.4  Iris-versicolor
52           6.9          3.1           4.9          1.5  Iris-versicolor
53           5.5          2.3           4.0          1.3  Iris-versicolor
54           6.5          2.8           4.6          1.5  Iris-versicolor

Lo mismo que antes pero muestre sólo esas dos columnas y la columna iris

In [53]:
# Escriba aqui su código
df_iris[df_iris.sepal_length > 2 * df_iris.sepal_width ][['sepal_width','sepal_length','iris']]

     sepal_width  sepal_length             iris
50           3.2           7.0  Iris-versicolor
52           3.1           6.9  Iris-versicolor
53           2.3           5.5  Iris-versicolor
54           2.8           6.5  Iris-versicolor
55           2.8           5.7  Iris-versicolor
..           ...           ...              ...
143          3.2           6.8   Iris-virginica
144          3.3           6.7   Iris-virginica
145          3.0           6.7   Iris-virginica
146          2.5           6.3   Iris-virginica
147          3.0           6.5   Iris-virginica

[79 rows x 3 columns]

Muestre qué valores **distintos** se han cargado en la columna iris.

In [54]:
#Escriba aquí su código
df_iris['iris'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

Queremos todas las filas para las cuales en la columna iris dice Iris-virginica. Muestre sólo las primeras 4

In [56]:
# Escriba aquí su código
df_iris[df_iris.iris == 'Iris-virginica'].head(4)

     sepal_length  sepal_width  petal_length  petal_width            iris
100           6.3          3.3           6.0          2.5  Iris-virginica
101           5.8          2.7           5.1          1.9  Iris-virginica
102           7.1          3.0           5.9          2.1  Iris-virginica
103           6.3          2.9           5.6          1.8  Iris-virginica

Cuando tenemos valores de cadena de texto suele ser útil el uso de:  

**columna.str.contains('cadena_de_caracteres')**   

Queremos todas las filas para las cuales en el texto cargado en la columna iris contiene v.

In [62]:
# Escriba aquí su código
df_iris[df_iris['iris'].str.contains('Iris-virginica')].head(4)

     sepal_length  sepal_width  petal_length  petal_width            iris
100           6.3          3.3           6.0          2.5  Iris-virginica
101           5.8          2.7           5.1          1.9  Iris-virginica
102           7.1          3.0           5.9          2.1  Iris-virginica
103           6.3          2.9           5.6          1.8  Iris-virginica

Queremos todas las filas para las cuales en el texto cargado en la columna iris contiene v y contiene la cadena 'color'

In [67]:
df_iris[(df_iris.iris.str.contains('v')) & (df_iris.iris.str.contains('color'))]

    sepal_length  sepal_width  petal_length  petal_width             iris
50           7.0          3.2           4.7          1.4  Iris-versicolor
51           6.4          3.2           4.5          1.5  Iris-versicolor
52           6.9          3.1           4.9          1.5  Iris-versicolor
53           5.5          2.3           4.0          1.3  Iris-versicolor
54           6.5          2.8           4.6          1.5  Iris-versicolor
55           5.7          2.8           4.5          1.3  Iris-versicolor
56           6.3          3.3           4.7          1.6  Iris-versicolor
57           4.9          2.4           3.3          1.0  Iris-versicolor
58           6.6          2.9           4.6          1.3  Iris-versicolor
59           5.2          2.7           3.9          1.4  Iris-versicolor
60           5.0          2.0           3.5          1.0  Iris-versicolor
61           5.9          3.0           4.2          1.5  Iris-versicolor
62           6.0          2.2           4.0          1.0  Iris-versicolor
63           6.1          2.9           4.7          1.4  Iris-versicolor
64           5.6          2.9           3.6          1.3  Iris-versicolor
65           6.7          3.1           4.4          1.4  Iris-versicolor
66           5.6          3.0           4.5          1.5  Iris-versicolor
67           5.8          2.7           4.1          1.0  Iris-versicolor
68           6.2          2.2           4.5          1.5  Iris-versicolor
69           5.6          2.5           3.9          1.1  Iris-versicolor
70           5.9          3.2           4.8          1.8  Iris-versicolor
71           6.1          2.8           4.0          1.3  Iris-versicolor
72           6.3          2.5           4.9          1.5  Iris-versicolor
73           6.1          2.8           4.7          1.2  Iris-versicolor
74           6.4          2.9           4.3          1.3  Iris-versicolor
75           6.6          3.0           4.4          1.4  Iris-versicolor
76           6.8          2.8           4.8          1.4  Iris-versicolor
77           6.7          3.0           5.0          1.7  Iris-versicolor
78           6.0          2.9           4.5          1.5  Iris-versicolor
79           5.7          2.6           3.5          1.0  Iris-versicolor
80           5.5          2.4           3.8          1.1  Iris-versicolor
81           5.5          2.4           3.7          1.0  Iris-versicolor
82           5.8          2.7           3.9          1.2  Iris-versicolor
83           6.0          2.7           5.1          1.6  Iris-versicolor
84           5.4          3.0           4.5          1.5  Iris-versicolor
85           6.0          3.4           4.5          1.6  Iris-versicolor
86           6.7          3.1           4.7          1.5  Iris-versicolor
87           6.3          2.3           4.4          1.3  Iris-versicolor
88           5.6          3.0           4.1          1.3  Iris-versicolor
89           5.5          2.5           4.0          1.3  Iris-versicolor
90           5.5          2.6           4.4          1.2  Iris-versicolor
91           6.1          3.0           4.6          1.4  Iris-versicolor
92           5.8          2.6           4.0          1.2  Iris-versicolor
93           5.0          2.3           3.3          1.0  Iris-versicolor
94           5.6          2.7           4.2          1.3  Iris-versicolor
95           5.7          3.0           4.2          1.2  Iris-versicolor
96           5.7          2.9           4.2          1.3  Iris-versicolor
97           6.2          2.9           4.3          1.3  Iris-versicolor
98           5.1          2.5           3.0          1.1  Iris-versicolor
99           5.7          2.8           4.1          1.3  Iris-versicolor

Queremos todas las filas para las cuales en el texto cargado en la columna iris contiene v o  contiene la cadena 'color'.

In [68]:
df_iris[(df_iris.iris.str.contains('v')) | (df_iris.iris.str.contains('color'))]

     sepal_length  sepal_width  petal_length  petal_width             iris
50            7.0          3.2           4.7          1.4  Iris-versicolor
51            6.4          3.2           4.5          1.5  Iris-versicolor
52            6.9          3.1           4.9          1.5  Iris-versicolor
53            5.5          2.3           4.0          1.3  Iris-versicolor
54            6.5          2.8           4.6          1.5  Iris-versicolor
..            ...          ...           ...          ...              ...
145           6.7          3.0           5.2          2.3   Iris-virginica
146           6.3          2.5           5.0          1.9   Iris-virginica
147           6.5          3.0           5.2          2.0   Iris-virginica
148           6.2          3.4           5.4          2.3   Iris-virginica
149           5.9          3.0           5.1          1.8   Iris-virginica

[100 rows x 5 columns]

Obviamente que   
**columna.str.contains('cadena_de_caracteres')**  

puede usarse con más de una caracter. En este caso buscará la cadena en cualquier parte del texto que figure en cada una de las celdas de esa columna. 

Si necesitamos una expresión más exacta, podemos usar **regex**, que tiene sus complicaciones, pero por ahora no entraremos en esos detalles.

Queremos todas las filas en las cuales el valor de iris contenga la cadena 'color'. Muestre sólo los últimos 4 registros

In [74]:
# Escriba aquí su código
df_iris[df_iris.iris.str.contains('color')].tail(4)

    sepal_length  sepal_width  petal_length  petal_width             iris
96           5.7          2.9           4.2          1.3  Iris-versicolor
97           6.2          2.9           4.3          1.3  Iris-versicolor
98           5.1          2.5           3.0          1.1  Iris-versicolor
99           5.7          2.8           4.1          1.3  Iris-versicolor

Queremos todas las filas cuyo texto en la columna iris no contenga la cadena *color*. Muestre las últimas 3 filsa.  

**Nota:** no existe el método "notcontains", asi que podría usar la idea de  negar el resultado de contains. Puede hacerlo de dos maneras usando **~** que es el operador para __negación__, o bien imponiendo en la condición que el resultado de contains()==False.

In [4]:
df_iris[~df_iris.iris.str.contains('color')].tail(3)

# otra opcion
#df_iris[~df_iris.iris.str.contains('color')==False].tail(3)

     sepal_length  sepal_width  petal_length  petal_width            iris
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

Queremos todas las filas para las cuales sepal_length es mayor a 4, petal_lenght menor a 3 y el texto cargado en iris no contiene la cadena color. Muestre las primeras 6 filas.   


Nota: use & para la operación lógica y en vez de and, suele ser necesario separar las pruebas lógicas escribiéndolas entre paréntesis.

In [7]:
# Escriba aquí su código
df_iris[(df_iris.sepal_length > 4) & (df_iris.petal_length < 3) & ~df_iris.iris.str.contains('color')].head(6)

   sepal_length  sepal_width  petal_length  petal_width         iris
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa

En la primer clase de Pandas vimos cómo calcular la media de los valores de una columna.

En qué observaciones el valor de sepal_length está por sobre la media? Muestre las 5 primeras filas.

In [10]:
df_iris.sepal_length.mean()

5.843333333333335

In [14]:
# Escriba aquí su código
df_iris[df_iris.sepal_length > df_iris.sepal_length.mean()].head(5)

    sepal_length  sepal_width  petal_length  petal_width             iris
50           7.0          3.2           4.7          1.4  Iris-versicolor
51           6.4          3.2           4.5          1.5  Iris-versicolor
52           6.9          3.1           4.9          1.5  Iris-versicolor
54           6.5          2.8           4.6          1.5  Iris-versicolor
56           6.3          3.3           4.7          1.6  Iris-versicolor

Ahora queremos ver todas las filas para las cuales el valor de sepal_length está por sobre la media y los valores de sepal_width están por debajo de la media.

In [16]:
df_iris.sepal_width.mean()

3.0540000000000007

In [15]:
# Escriba aquí su código
df_iris[(df_iris.sepal_length > df_iris.sepal_length.mean())&(df_iris.sepal_width < df_iris.sepal_width.mean())]

     sepal_length  sepal_width  petal_length  petal_width             iris
54            6.5          2.8           4.6          1.5  Iris-versicolor
58            6.6          2.9           4.6          1.3  Iris-versicolor
61            5.9          3.0           4.2          1.5  Iris-versicolor
62            6.0          2.2           4.0          1.0  Iris-versicolor
63            6.1          2.9           4.7          1.4  Iris-versicolor
68            6.2          2.2           4.5          1.5  Iris-versicolor
71            6.1          2.8           4.0          1.3  Iris-versicolor
72            6.3          2.5           4.9          1.5  Iris-versicolor
73            6.1          2.8           4.7          1.2  Iris-versicolor
74            6.4          2.9           4.3          1.3  Iris-versicolor
75            6.6          3.0           4.4          1.4  Iris-versicolor
76            6.8          2.8           4.8          1.4  Iris-versicolor
77            6.7          3.0           5.0          1.7  Iris-versicolor
78            6.0          2.9           4.5          1.5  Iris-versicolor
83            6.0          2.7           5.1          1.6  Iris-versicolor
87            6.3          2.3           4.4          1.3  Iris-versicolor
91            6.1          3.0           4.6          1.4  Iris-versicolor
97            6.2          2.9           4.3          1.3  Iris-versicolor
102           7.1          3.0           5.9          2.1   Iris-virginica
103           6.3          2.9           5.6          1.8   Iris-virginica
104           6.5          3.0           5.8          2.2   Iris-virginica
105           7.6          3.0           6.6          2.1   Iris-virginica
107           7.3          2.9           6.3          1.8   Iris-virginica
108           6.7          2.5           5.8          1.8   Iris-virginica
111           6.4          2.7           5.3          1.9   Iris-virginica
112           6.8          3.0           5.5          2.1   Iris-virginica
116           6.5          3.0           5.5          1.8   Iris-virginica
118           7.7          2.6           6.9          2.3   Iris-virginica
119           6.0          2.2           5.0          1.5   Iris-virginica
122           7.7          2.8           6.7          2.0   Iris-virginica
123           6.3          2.7           4.9          1.8   Iris-virginica
126           6.2          2.8           4.8          1.8   Iris-virginica
127           6.1          3.0           4.9          1.8   Iris-virginica
128           6.4          2.8           5.6          2.1   Iris-virginica
129           7.2          3.0           5.8          1.6   Iris-virginica
130           7.4          2.8           6.1          1.9   Iris-virginica
132           6.4          2.8           5.6          2.2   Iris-virginica
133           6.3          2.8           5.1          1.5   Iris-virginica
134           6.1          2.6           5.6          1.4   Iris-virginica
135           7.7          3.0           6.1          2.3   Iris-virginica
138           6.0          3.0           4.8          1.8   Iris-virginica
145           6.7          3.0           5.2          2.3   Iris-virginica
146           6.3          2.5           5.0          1.9   Iris-virginica
147           6.5          3.0           5.2          2.0   Iris-virginica
149           5.9          3.0           5.1          1.8   Iris-virginica

Ahora queremos las filas en las cuales la media de sepal_length **o** la media de sepal_width están por sobre sus respectivas medias.

In [17]:
# Escriba aquí su código
df_iris[(df_iris.sepal_length < df_iris.sepal_length.mean()) | (df_iris.sepal_width < df_iris.sepal_width.mean())]

     sepal_length  sepal_width  petal_length  petal_width            iris
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
142           5.8          2.7           5.1          1.9  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[125 rows x 5 columns]

## FORMAS DE ORDENAR

### Ordenando las filas por los valores de una columna

Si queremos ordenar el dataframe por los valores de una fila, podemos usar:  

**DataFrame.sort_values()** 

Documentación: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html

En este caso es interesante observar sus argumentos, véalos en la documentación indicada.

Obtengamos un duplicado de df_iris, de tal forma que sus filas estén ordenadas por las columna iris en formas ascendente, es decir de a a la z.

In [69]:
df_iris.sort_values('iris')

     sepal_length  sepal_width  petal_length  petal_width            iris
0             5.1          3.5           1.4          0.2     Iris-setosa
27            5.2          3.5           1.5          0.2     Iris-setosa
28            5.2          3.4           1.4          0.2     Iris-setosa
29            4.7          3.2           1.6          0.2     Iris-setosa
30            4.8          3.1           1.6          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
119           6.0          2.2           5.0          1.5  Iris-virginica
120           6.9          3.2           5.7          2.3  Iris-virginica
121           5.6          2.8           4.9          2.0  Iris-virginica
111           6.4          2.7           5.3          1.9  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

Obtengamos un duplicado de df_iris, de tal forma que sus filas estén ordenadas por las columna iris en formas descendente, es decir de la z a la a.

In [70]:
# Escriba aquí su código
df_iris.sort_values('iris',ascending = False)

     sepal_length  sepal_width  petal_length  petal_width            iris
149           5.9          3.0           5.1          1.8  Iris-virginica
111           6.4          2.7           5.3          1.9  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
121           5.6          2.8           4.9          2.0  Iris-virginica
120           6.9          3.2           5.7          2.3  Iris-virginica
..            ...          ...           ...          ...             ...
31            5.4          3.4           1.5          0.4     Iris-setosa
30            4.8          3.1           1.6          0.2     Iris-setosa
29            4.7          3.2           1.6          0.2     Iris-setosa
28            5.2          3.4           1.4          0.2     Iris-setosa
0             5.1          3.5           1.4          0.2     Iris-setosa

[150 rows x 5 columns]

### Ordenando las filas por los valores de varias columnas:

Cuando se ordena por los valores de varias columnas es importante tener en cuenta qué significa.  
Supongamos que tenemos un df con las columnas Apellido y Nombre y asumamos que queremos ordenarla por las columnas Apellido (primero) y (luego por ) las columna nombre.  

Esto significa que el ordenamiento principal será por Apellido y en el caso que "haya empate" en el valor del apellido, entonces desempatará con el valor de la columna Nombre.

Ordenar en forma ascendente a df_iris primero por la columna iris y luego por la columna sepal_length. Muestre los primero 6 casos. En este caso, cuando tenemos varias columnas para ordenar, debemos pasar los valores de las columnas como array.

In [71]:
df_iris.sort_values(['iris','sepal_length'],ascending = False)

     sepal_length  sepal_width  petal_length  petal_width            iris
131           7.9          3.8           6.4          2.0  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
..            ...          ...           ...          ...             ...
41            4.5          2.3           1.3          0.3     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
38            4.4          3.0           1.3          0.2     Iris-setosa
42            4.4          3.2           1.3          0.2     Iris-setosa
13            4.3          3.0           1.1          0.1     Iris-setosa

[150 rows x 5 columns]

Ahora ordene por las columnas iris, sepal_length y sepal_width, en ese orden.

In [73]:
# Escriba aquí su código
df_iris.sort_values(['iris','sepal_length','sepal_width'])

     sepal_length  sepal_width  petal_length  petal_width            iris
13            4.3          3.0           1.1          0.1     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
38            4.4          3.0           1.3          0.2     Iris-setosa
42            4.4          3.2           1.3          0.2     Iris-setosa
41            4.5          2.3           1.3          0.3     Iris-setosa
..            ...          ...           ...          ...             ...
118           7.7          2.6           6.9          2.3  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica

[150 rows x 5 columns]

Qué pasará si queremos ordenar por una columna en forma ascendente y por otra en forma descendente?  
Ayuda, de la misma manera que podemos pasar varias columnas en un array, también podemos hacer lo mismo para el valor del  atributo **ascending** ... 

Ordene df_iris primero por la columna iris en forma descendente y luego por la columna sepal_length en forma ascendente. Muestre las 6 primeras filas.

In [18]:
# Escriba aquí su código
df_iris.sort_values(['iris','sepal_length'],ascending = False)