#Preprocesamiento

#### Ejercicio 1

Supongamos que tenemos el dataframe dfB, y queremos imputar o asignar el valor de la **mediana** a los valores nulos (nan) de todas sus columnas.   
Al imputador ll√°melo imputador1 y guarde los resultados ya transformados en un DataFrame denominado dfB_Transformado.

In [ ]:
dfB=pd.DataFrame([[1,5,4,3],[np.nan,3,2,np.nan],[7,np.nan,0,4],[4,2,4,1],[3,0,np.nan,8],[2,7,5,4]])
dfB.columns=['col1','col2','col3','col4']
dfB

   col1  col2  col3  col4
0   1.0   5.0   4.0   3.0
1   NaN   3.0   2.0   NaN
2   7.0   NaN   0.0   4.0
3   4.0   2.0   4.0   1.0
4   3.0   0.0   NaN   8.0
5   2.0   7.0   5.0   4.0

In [ ]:
imputador1 = SimpleImputer(strategy='median')#Creo el modelo
imputador1.fit(dfB)#Lo entreno con los datos que quiero

SimpleImputer(strategy='median')

In [ ]:
imputador1.statistics_#Observo los datos para estar seguro

array([3., 3., 4., 4.])

In [ ]:
ArrayB_Transformado = imputador1.transform(dfB)# Creo un array de los nuevos datos
ArrayB_Transformado# lo visualizo

array([[1., 5., 4., 3.],
       [3., 3., 2., 4.],
       [7., 3., 0., 4.],
       [4., 2., 4., 1.],
       [3., 0., 4., 8.],
       [2., 7., 5., 4.]])

In [ ]:
dfB_transformado = pd.DataFrame(ArrayB_Transformado, columns=dfB.columns) # Creo el DF con los datos del array y Le asigno las columnas del viejo DF
dfB_transformado # Lo muestro

   col1  col2  col3  col4
0   1.0   5.0   4.0   3.0
1   3.0   3.0   2.0   4.0
2   7.0   3.0   0.0   4.0
3   4.0   2.0   4.0   1.0
4   3.0   0.0   4.0   8.0
5   2.0   7.0   5.0   4.0

En forma corta el flujo ser√≠an nuestros 3 pasos, crear el imputador, entrenarlo y aplicarlo:

In [ ]:
imputador1=SimpleImputer(missing_values=np.nan,strategy='median') # creamos
imputador1.fit(dfB)                                               # entrenamos
B_Transformado=imputador1.transform(dfB)                          # imputamos

B_Transformado

array([[1., 5., 4., 3.],
       [3., 3., 2., 4.],
       [7., 3., 0., 4.],
       [4., 2., 4., 1.],
       [3., 0., 4., 8.],
       [2., 7., 5., 4.]])

Hemos obtenido los valores ya transformados pero como array de Numpy, si es necesario podemos transformarlo en un dataFrame con los mismos nombres de columnas que el original.

In [ ]:
# lo que sigue es s√≥lo para rearmarlo como DataFrame, si es necesario y luego mostrarlo:
dfB_Transformado=pd.DataFrame(B_Transformado, columns=dfB.columns)
dfB_Transformado

   col1  col2  col3  col4
0   1.0   5.0   4.0   3.0
1   3.0   3.0   2.0   4.0
2   7.0   3.0   0.0   4.0
3   4.0   2.0   4.0   1.0
4   3.0   0.0   4.0   8.0
5   2.0   7.0   5.0   4.0

Como puede observar, realmente muy sencillo! Veamos algunos casos m√°s.

#### Ejercicio 2  

Dado el DataFrame dfC, impute la mediana de cada columna a los valores que tienen valor -1. Al imputador ll√°melo imputador2 y guarde los resultados en un nuevo dataFrame denominado dfC_Transformado

In [ ]:
dfC=pd.DataFrame([[3,7,-1,0],[2,-1,5,4],[0,0,0,0],[-1,5,4,2],[2,6,8,1],[2,1,3,2]])
dfC.columns=['A','B','C','D']
dfC

   A  B  C  D
0  3  7 -1  0
1  2 -1  5  4
2  0  0  0  0
3 -1  5  4  2
4  2  6  8  1
5  2  1  3  2

#### Respuesta Ejercicio 2

En forma corta el flujo ser√≠a:

In [ ]:
imputador2 = SimpleImputer(strategy='median',missing_values=-1)
imputador2.fit(dfC)
imputador2.statistics_

array([2. , 5. , 4. , 1.5])

In [ ]:
dfC_transformado = pd.DataFrame(imputador2.transform(dfC),columns=dfC.columns) #hice la tranfromacion dentro de la creacion del data frame
dfC_transformado

     A    B    C    D
0  3.0  7.0  4.0  0.0
1  2.0  5.0  5.0  4.0
2  0.0  0.0  0.0  0.0
3  2.0  5.0  4.0  2.0
4  2.0  6.0  8.0  1.0
5  2.0  1.0  3.0  2.0

#### Ejercicio 3  
Vamos a complicarla un poco:  
    

Dado el DataFrame dfC: 

- En las columnas A y C, impute a los valores -1, el promedio. Llame a este imputador imputador_prom
- En las columnas B y D impute a los valores -1 la mediana. Llame a este imputador imputador_mediana

Guarde los resutados en un nuevo DataFrame denominado dfC_Transformado2

#### Respuesta Ejercicio 3:

Como el imputador de sklearn trabaja sobre **todas** las columnas ... y queremos hacer imputaciones distintas a algunas columnas ... deberemos dividir nuestro dataframe original en dos partes, uno que tenga las columnas A y C y otro que tenga las columnas B y D.

In [ ]:
dfC1=dfC[['A','C']]
dfC1

   A  C
0  3 -1
1  2  5
2  0  0
3 -1  4
4  2  8
5  2  3

Ahora trabajamos con las imputaciones para estas columnas:

In [ ]:
imputadorC1= SimpleImputer(missing_values=-1,strategy='mean')
imputadorC1.fit(dfC1)
imputadorC1.statistics_

array([1.8, 4. ])

In [ ]:
dfC1_transformado= pd.DataFrame(imputadorC1.transform(dfC1),columns=dfC1.columns)
dfC1_transformado

     A    C
0  3.0  4.0
1  2.0  5.0
2  0.0  0.0
3  1.8  4.0
4  2.0  8.0
5  2.0  3.0

Ahora repetimos las operaciones para las columnas B y D:

In [ ]:
dfC2 = dfC[['B','D']]
dfC2

   B  D
0  7  0
1 -1  4
2  0  0
3  5  2
4  6  1
5  1  2

Ahora trabajamos con las imputaciones para estas columnas:

In [ ]:
imputadorC2 = SimpleImputer(missing_values=-1,strategy='median')
imputadorC2.fit(dfC2)
imputadorC2.statistics_

array([5. , 1.5])

In [ ]:
dfC2_transformado = pd.DataFrame(imputadorC2.transform(dfC2), columns=dfC2.columns)
dfC2_transformado

     B    D
0  7.0  0.0
1  5.0  4.0
2  0.0  0.0
3  5.0  2.0
4  6.0  1.0
5  1.0  2.0

Si lo necesitamos (no siempre es necesario), podr√≠amos reconstruir el DataFrame con todas sus columnas pero ahora transformadas, para ello deberemos  utilizar un poco de Pandas ... podemos usar pd.concat() ... (hay muchas otras formas de hacerlo):

In [ ]:
dfC_Final = pd.concat([dfC1_transformado,dfC2_transformado],axis=1)
dfC_Final

     A    C    B    D
0  3.0  4.0  7.0  0.0
1  2.0  5.0  5.0  4.0
2  0.0  0.0  0.0  0.0
3  1.8  4.0  5.0  2.0
4  2.0  8.0  6.0  1.0
5  2.0  3.0  1.0  2.0

#### Ejercicio 4

Supongamos que tenemos un DataFrame como el dfD:

In [ ]:
dfD=pd.DataFrame([[3,2,'Si'],[np.nan,6,'No'],[5,8,'Si'],[0,np.nan,'Si'],[np.nan,4,'No'],[6,6,np.nan],[4,12,'No'],[2,9,np.nan]])
dfD.columns=['x1','x2','x3']
dfD

    x1    x2   x3
0  3.0   2.0   Si
1  NaN   6.0   No
2  5.0   8.0   Si
3  0.0   NaN   Si
4  NaN   4.0   No
5  6.0   6.0  NaN
6  4.0  12.0   No
7  2.0   9.0  NaN

Observe que la variable x3 no es num√©rica, sino categ√≥rica.

Queremos imputar el promedio en las columnas num√©ricas y la moda en las columnas categ√≥ricas (esto es un problema bien t√≠pico de ML).  Queremos el resultado en un √∫nico DataFrame que se llame dfD_Transformado.

In [ ]:
dfD_cat = pd.DataFrame(dfD['x3'])
dfD_cat

    x3
0   Si
1   No
2   Si
3   Si
4   No
5  NaN
6   No
7  NaN

In [ ]:
imputadorD_cat = SimpleImputer(strategy='most_frequent')#Creo el modelo imputer
imputadorD_cat.fit(dfD_cat)#Lo entreno con los datos de las variables categoricas
imputadorD_cat.statistics_#Hago que me muestre cual resultado obtuvo
dfD_cat_transformado = pd.DataFrame(imputadorD_cat.transform(dfD_cat),columns=(['x3'])) # Creo el nuevo DF
dfD_cat_transformado# Muestro el nuevo DF

   x3
0  Si
1  No
2  Si
3  Si
4  No
5  No
6  No
7  No

In [ ]:
dfD_num = dfD[['x1','x2']]
dfD_num

    x1    x2
0  3.0   2.0
1  NaN   6.0
2  5.0   8.0
3  0.0   NaN
4  NaN   4.0
5  6.0   6.0
6  4.0  12.0
7  2.0   9.0

In [ ]:
imputadorD_num = SimpleImputer(strategy='mean')#Creo el modelo con el promedio
imputadorD_num.fit(dfD_num)#lo hago calcular las variables
imputadorD_num.statistics_#Evaluo los resultados

array([3.33333333, 6.71428571])

In [ ]:
dfD_num_transformado = pd.DataFrame( imputadorD_num.transform(dfD_num) ,columns=('x1','x2'))
dfD_num_transformado

         x1         x2
0  3.000000   2.000000
1  3.333333   6.000000
2  5.000000   8.000000
3  0.000000   6.714286
4  3.333333   4.000000
5  6.000000   6.000000
6  4.000000  12.000000
7  2.000000   9.000000

In [ ]:
dfD_Final = pd.concat([dfD_num_transformado,dfD_cat_transformado],axis=1)
dfD_Final

         x1         x2  x3
0  3.000000   2.000000  Si
1  3.333333   6.000000  No
2  5.000000   8.000000  Si
3  0.000000   6.714286  Si
4  3.333333   4.000000  No
5  6.000000   6.000000  No
6  4.000000  12.000000  No
7  2.000000   9.000000  No

#### Ejercicio 6
Supongamos que contamos con el DataFrame dfE:

In [ ]:
dfE=pd.DataFrame([[1.5,'Si',2,True],[4,'No',7,False],[np.nan,'Si',9,False],[3.5,np.nan,8,np.nan],[6,'Si',np.nan,True]])
dfE.columns=['x1','x2','x3','x4']
dfE

    x1   x2   x3     x4
0  1.5   Si  2.0   True
1  4.0   No  7.0  False
2  NaN   Si  9.0  False
3  3.5  NaN  8.0    NaN
4  6.0   Si  NaN   True

y queremos imputar: 
- el **promedio** a las num√©ricas y,
- la **moda** a las categ√≥ricas, de texto y booleanas, 
- el resultado lo queremos en el DataFrame denominado dfE_Transformado

Veamos de qu√© tipo es cada columna con info()

In [ ]:
dfE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      4 non-null      float64
 1   x2      4 non-null      object
 2   x3      4 non-null      float64
 3   x4      4 non-null      object
dtypes: float64(2), object(2)
memory usage: 288.0+ bytes

- A x1 y x3 las tom√≥ como float64, es decir num√©ricas, si hubieran sido n√∫meros enteros las hubier considerado como int64. No hay diferencia para la imputaci√≥n.  

- A x2 la tom√≥ como object, que es el tipo correspondiente a los textos y categ√≥ricas.  

- F√≠jese que a la columna x4 la tom√≥ como object cuando los valores eran esencialmente booleanos, esto ocurri√≥ por la presencial del nan. Generalmente no traer√° problemas porque en ambos casos la imputaci√≥n suele ser la moda.

Esta vez no queremos pasar expl√≠citamente los nombres de cada columna a cada trasnformer, sino que buscamos alguna manera de hacerlo program√°ticamente.  

Podemos usar a select_dtypes de Pandas para seleccionar las columnas seg√∫n el tipo de dato:

In [ ]:
cols_num=dfE.select_dtypes(np.number).columns
# en vez de np.number podriamos haber usado select_dtypes.(include=['int64','float64']).columns
cols_num

Index(['x1', 'x3'], dtype='object')

Como podemos ver, nos devolvi√≥ x1 y x3 como dese√°bamos. De forma similar:

In [ ]:
cols_cat=dfE.select_dtypes(include=['object','bool']).columns
cols_cat

Index(['x2', 'x4'], dtype='object')

Nos devolvi√≥ x2 y x4

Ahora s√≠, estamos listos! Se anima a terminarlo?

#### Resoluci√≥n Ejercicio 6

Son s√≥lo unas pocas l√≠neas de c√≥digo!

In [ ]:
t1E = ('mod_num',SimpleImputer(strategy='mean'),cols_num)
t2E = ('mod_cat', SimpleImputer(strategy='most_frequent'),cols_cat)

transformador_E_columnas = ColumnTransformer(transformers=[t1E,t2E])

transformador_E_columnas.fit(dfE)

ColumnTransformer(transformers=[('mod_num', SimpleImputer(),
                                 Index(['x1', 'x3'], dtype='object')),
                                ('mod_cat',
                                 SimpleImputer(strategy='most_frequent'),
                                 Index(['x2', 'x4'], dtype='object'))])

Lo transformamos en un DataFrame de Pandas seg√∫n lo solicitado:

In [ ]:
dfE_transformado = pd.DataFrame(transformador_E_columnas.transform(dfE), columns= dfE.columns)
dfE_transformado

     x1   x2  x3     x4
0   1.5  2.0  Si   True
1   4.0  7.0  No  False
2  3.75  9.0  Si  False
3   3.5  8.0  Si  False
4   6.0  6.5  Si   True

Listo!